/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Donation: () => import('#controllers/donation_controller'),
  Event: () => import('#controllers/event_controller'),
  Gift: () => import('#controllers/gift_controller'),
  PurchaseConfirmation: () => import('#controllers/purchase_confirmation_controller'),
  Rsvp: () => import('#controllers/rsvp_controller'),
}
