/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Event: () => import('#controllers/event_controller'),
  Rsvp: () => import('#controllers/rsvp_controller'),
}
