/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AdminDonation: () => import('#controllers/admin_donation_controller'),
  AdminGift: () => import('#controllers/admin_gift_controller'),
  AdminGuest: () => import('#controllers/admin_guest_controller'),
  AdminPurchaseConfirmation: () => import('#controllers/admin_purchase_confirmation_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Donation: () => import('#controllers/donation_controller'),
  EventAdmin: () => import('#controllers/event_admin_controller'),
  Event: () => import('#controllers/event_controller'),
  Gift: () => import('#controllers/gift_controller'),
  PurchaseConfirmation: () => import('#controllers/purchase_confirmation_controller'),
  Rsvp: () => import('#controllers/rsvp_controller'),
}
